name: Building Docker image
run-name: ${{ github.actor }} is building docker image 🚀
on:
  push:
    branches:
      - fin
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: vanshbehal01
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image and push to docker hub
        run: |
          ls
          docker build -t vanshbehal01/face-recognition:backend .
          docker push vanshbehal01/face-recognition:backend
